version: '3.1'

services:
  db: 
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: store
    ports:
      - 5432:5432

  flyway_postgres:
    depends_on:
      - db
    image: flyway/flyway
    build: ./flyway
    volumes:
      - ./flyway/config:/flyway/conf
      - ./flyway/sql:/flyway/sql